export const frameworks = [
  {
    id: 1,
    name: 'React',
    img: '/images/react.svg',
    popularity: 1, // Most popular

    // 1
    recommended_experience_level: 'beginner',

    // 2
    project_compatibility: {
      landing_page: 4,
      blog: 4,
      spa: 5,
      mpa: 3,
      dashboard: 5,
      ecommerce: 5,
    },

    // 3
    learning_curve: 3,

    // 4
    performance: 4,

    // 5
    seo_support: 3,

    // 6
    team_adaptation: {
      individual: 5,
      small_team: 5,
      large_team: 4,
    },

    // 7
    required_js_experience: 'intermediate',

    // 8
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },

    // 9
    community: 5,
    documentation: 5,

    // 10
    scalability: 5,
    ease_of_maintenance: 4,

    // other
    mobile_compatibility: 4,
    structure_flexibility: 5,
    ecosystem: 5,
    job_market_popularity: 5,
    documentation_url: 'https://reactjs.org/docs/getting-started.html',
  },
  {
    id: 2,
    name: 'Vue.js',
    img: '/images/vue.svg',
    popularity: 3,
    recommended_experience_level: 'beginner',
    project_compatibility: {
      landing_page: 5,
      blog: 4,
      spa: 5,
      mpa: 4,
      dashboard: 5,
      ecommerce: 4,
    },
    learning_curve: 2,
    performance: 4,
    seo_support: 3,
    team_adaptation: {
      individual: 5,
      small_team: 5,
      large_team: 4,
    },
    required_js_experience: 'basic',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: true,
    },
    community: 4,
    documentation: 5,
    scalability: 4,
    ease_of_maintenance: 5,
    mobile_compatibility: 4,
    structure_flexibility: 5,
    ecosystem: 4,
    job_market_popularity: 4,
    documentation_url: 'https://vuejs.org/guide/introduction.html',
  },
  {
    id: 3,
    name: 'Angular',
    img: '/images/angular.svg',
    popularity: 4,
    recommended_experience_level: 'advanced',
    project_compatibility: {
      landing_page: 3,
      blog: 3,
      spa: 5,
      mpa: 3,
      dashboard: 5,
      ecommerce: 5,
    },
    learning_curve: 5,
    performance: 4,
    seo_support: 3,
    team_adaptation: {
      individual: 3,
      small_team: 4,
      large_team: 5,
    },
    required_js_experience: 'advanced',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 4,
    documentation: 5,
    scalability: 5,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 3,
    ecosystem: 5,
    job_market_popularity: 4,
    documentation_url: 'https://angular.io/docs',
  },
  {
    id: 4,
    name: 'Next.js',
    img: '/images/next-js.svg',
    popularity: 2,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 5,
      blog: 5,
      spa: 5,
      mpa: 5,
      dashboard: 5,
      ecommerce: 5,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 5,
    team_adaptation: {
      individual: 4,
      small_team: 5,
      large_team: 5,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 5,
    documentation: 5,
    scalability: 5,
    ease_of_maintenance: 4,
    mobile_compatibility: 5,
    structure_flexibility: 4,
    ecosystem: 5,
    job_market_popularity: 5,
    documentation_url: 'https://nextjs.org/docs',
  },
  {
    id: 5,
    name: 'Svelte',
    img: '/images/svelte.svg',
    popularity: 8,
    recommended_experience_level: 'beginner',
    project_compatibility: {
      landing_page: 5,
      blog: 4,
      spa: 5,
      mpa: 3,
      dashboard: 4,
      ecommerce: 3,
    },
    learning_curve: 2,
    performance: 5,
    seo_support: 3,
    team_adaptation: {
      individual: 5,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'basic',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: true,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 5,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 3,
    job_market_popularity: 3,
    documentation_url: 'https://svelte.dev/docs',
  },
  {
    id: 6,
    name: 'Nuxt.js',
    img: '/images/nuxt-js.svg',
    popularity: 6,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 5,
      blog: 5,
      spa: 5,
      mpa: 5,
      dashboard: 4,
      ecommerce: 5,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 5,
    team_adaptation: {
      individual: 4,
      small_team: 5,
      large_team: 4,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 4,
    documentation: 4,
    scalability: 5,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 4,
    job_market_popularity: 4,
    documentation_url: 'https://nuxtjs.org/docs',
  },
  {
    id: 7,
    name: 'Ember.js',
    img: '/images/ember.svg',
    popularity: 14,
    recommended_experience_level: 'advanced',
    project_compatibility: {
      landing_page: 3,
      blog: 4,
      spa: 5,
      mpa: 3,
      dashboard: 5,
      ecommerce: 4,
    },
    learning_curve: 4,
    performance: 3,
    seo_support: 3,
    team_adaptation: {
      individual: 2,
      small_team: 3,
      large_team: 5,
    },
    required_js_experience: 'advanced',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 3,
    mobile_compatibility: 3,
    structure_flexibility: 2,
    ecosystem: 3,
    job_market_popularity: 2,
    documentation_url: 'https://guides.emberjs.com',
  },
  {
    id: 8,
    name: 'SvelteKit',
    img: '/images/svelte.svg',
    popularity: 7,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 5,
      blog: 5,
      spa: 5,
      mpa: 5,
      dashboard: 4,
      ecommerce: 4,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 5,
    team_adaptation: {
      individual: 5,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 3,
    job_market_popularity: 3,
    documentation_url: 'https://kit.svelte.dev/docs',
  },
  {
    id: 9,
    name: 'Preact',
    img: '/images/preact.svg',
    popularity: 11,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 4,
      blog: 4,
      spa: 5,
      mpa: 3,
      dashboard: 4,
      ecommerce: 4,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 3,
    team_adaptation: {
      individual: 5,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 4,
    mobile_compatibility: 5,
    structure_flexibility: 5,
    ecosystem: 3,
    job_market_popularity: 3,
    documentation_url: 'https://preactjs.com/guide/v10/getting-started',
  },
  {
    id: 10,
    name: 'Astro',
    img: '/images/astro-js.svg',
    popularity: 9,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 5,
      blog: 5,
      spa: 3,
      mpa: 5,
      dashboard: 3,
      ecommerce: 4,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 5,
    team_adaptation: {
      individual: 5,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: false,
      authentication: true,
      standalone: false,
    },
    community: 4,
    documentation: 5,
    scalability: 4,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 3,
    job_market_popularity: 3,
    documentation_url: 'https://docs.astro.build',
  },
  {
    id: 11,
    name: 'Qwik',
    img: '/images/qwik.svg',
    popularity: 13,
    recommended_experience_level: 'advanced',
    project_compatibility: {
      landing_page: 5,
      blog: 4,
      spa: 4,
      mpa: 5,
      dashboard: 4,
      ecommerce: 4,
    },
    learning_curve: 4,
    performance: 5,
    seo_support: 5,
    team_adaptation: {
      individual: 4,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'advanced',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 3,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 2,
    job_market_popularity: 2,
    documentation_url: 'https://qwik.builder.io/docs/',
  },
  {
    id: 12,
    name: 'Alpine.js',
    img: '/images/alpine-js.svg',
    popularity: 10,
    recommended_experience_level: 'beginner',
    project_compatibility: {
      landing_page: 5,
      blog: 4,
      spa: 3,
      mpa: 5,
      dashboard: 3,
      ecommerce: 3,
    },
    learning_curve: 1,
    performance: 4,
    seo_support: 5,
    team_adaptation: {
      individual: 5,
      small_team: 4,
      large_team: 2,
    },
    required_js_experience: 'basic',
    integrations: {
      rest_api: true,
      real_time: false,
      authentication: false,
      standalone: true,
    },
    community: 3,
    documentation: 4,
    scalability: 3,
    ease_of_maintenance: 5,
    mobile_compatibility: 5,
    structure_flexibility: 4,
    ecosystem: 2,
    job_market_popularity: 2,
    documentation_url: 'https://alpinejs.dev/start-here',
  },
  {
    id: 13,
    name: 'Solid.js',
    img: '/images/solidjs.svg',
    popularity: 12,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 4,
      blog: 4,
      spa: 5,
      mpa: 3,
      dashboard: 5,
      ecommerce: 4,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 3,
    team_adaptation: {
      individual: 5,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 3,
    job_market_popularity: 2,
    documentation_url: 'https://www.solidjs.com/guides/getting-started',
  },
  {
    id: 14,
    name: 'Remix',
    img: '/images/remix.svg',
    popularity: 5,
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 4,
      blog: 5,
      spa: 5,
      mpa: 5,
      dashboard: 5,
      ecommerce: 5,
    },
    learning_curve: 4,
    performance: 5,
    seo_support: 5,
    team_adaptation: {
      individual: 4,
      small_team: 5,
      large_team: 4,
    },
    required_js_experience: 'advanced',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: false,
    },
    community: 4,
    documentation: 4,
    scalability: 5,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 3,
    ecosystem: 4,
    job_market_popularity: 3,
    documentation_url: 'https://remix.run/docs/en/main',
  },
  {
    id: 15,
    name: 'Lit',
    img: '/images/lit.svg',
    popularity: 15, // Least popular
    recommended_experience_level: 'intermediate',
    project_compatibility: {
      landing_page: 4,
      blog: 3,
      spa: 4,
      mpa: 4,
      dashboard: 4,
      ecommerce: 3,
    },
    learning_curve: 3,
    performance: 5,
    seo_support: 4,
    team_adaptation: {
      individual: 4,
      small_team: 4,
      large_team: 3,
    },
    required_js_experience: 'intermediate',
    integrations: {
      rest_api: true,
      real_time: true,
      authentication: true,
      standalone: true,
    },
    community: 3,
    documentation: 4,
    scalability: 4,
    ease_of_maintenance: 4,
    mobile_compatibility: 4,
    structure_flexibility: 4,
    ecosystem: 3,
    job_market_popularity: 2,
    documentation_url: 'https://lit.dev/docs/',
  },
]

export const questions = [
  {
    id: 1,
    question: 'What is your level of experience in web development?',
    options: [
      { id: 'b', text: 'Beginner (< 1 year)' },
      { id: 'i', text: 'Intermediate (1–3 years)' },
      { id: 'a', text: 'Advanced (> 3 years)' },
    ],
  },
  {
    id: 2,
    question: 'What type of application are you planning to build?',
    options: [
      { id: 'info', text: 'Landing page (static or promotional content)' },
      {
        id: 'blog',
        text: 'Blog or content site (frequent updates, content management)',
      },
      {
        id: 'spa',
        text: 'Single-page application (SPA – dynamic navigation, single initial load)',
      },
      {
        id: 'mpa',
        text: 'Multi-page application (MPA – each view loads a new page)',
      },
      {
        id: 'dash',
        text: 'Dashboard or admin panel (interface to manage data or users)',
      },
      {
        id: 'ecom',
        text: 'Online store / E-commerce (product catalog, shopping cart, payments)',
      },
    ],
  },
  {
    id: 3,
    question:
      'Do you prefer a framework that is easy to learn or more powerful?',
    options: [
      { id: 'quick', text: 'I prefer something simple and quick to learn' },
      {
        id: 'complex',
        text: 'I prefer more functionality, even if it takes longer to learn',
      },
      {
        id: 'balance',
        text: "I'm looking for a balance between ease of use and power",
      },
    ],
  },
  {
    id: 4,
    question: 'How important is performance for your project?',
    options: [
      { id: 'cri', text: 'High performance is critical' },
      { id: 'imp', text: 'Performance is important but not crucial' },
      { id: 'neu', text: 'Standard performance is sufficient' },
    ],
  },
  {
    id: 5,
    question: 'Does your application need to be SEO-friendly?',
    options: [
      { id: 'yes', text: 'Yes, SEO is very important' },
      { id: 'helpful', text: "It would be helpful, but it's not essential" },
      { id: 'no', text: 'Not a priority' },
    ],
  },
  {
    id: 6,
    question: 'What is the size of your development team?',
    options: [
      { id: 'solo', text: 'Just me' },
      { id: 'small', text: 'Small team (2–5 people)' },
      { id: 'large', text: 'Large team (> 5 people)' },
    ],
  },
  {
    id: 7,
    question: 'What is your experience with JavaScript?',
    options: [
      { id: 'b', text: 'Basic (DOM manipulation, simple events)' },
      { id: 'i', text: 'Intermediate (ES6+, promises, async/await)' },
      { id: 'a', text: 'Advanced (design patterns, frameworks)' },
    ],
  },
  {
    id: 8,
    question: 'Do you plan to integrate your application with other systems?',
    options: [
      { id: 'apis', text: 'Yes, with REST APIs' },
      { id: 'db', text: 'Yes, with real-time databases' },
      { id: 'auth', text: 'Yes, with authentication systems' },
      { id: 'no', text: 'No, it will be a standalone application' },
    ],
  },
  {
    id: 9,
    question: "How important is the framework's community and documentation?",
    options: [
      {
        id: 'very',
        text: 'Very important — I want to easily find answers and support',
      },
      { id: 'useful', text: 'Useful, but not a deciding factor' },
      { id: 'not', text: "Not something I'm concerned about" },
    ],
  },
  {
    id: 10,
    question: 'How important is long-term maintainability and scalability?',
    options: [
      {
        id: 'very',
        text: 'Very important — I plan to maintain and scale the project',
      },
      { id: 'imp', text: 'Important, but the project is short to mid-term' },
      { id: 'not', text: "Not a priority — it's a small or temporary project" },
    ],
  },
]
