export const frameworks = [
  {
    id: 1,
    nombre: 'React',
    nivel_experiencia_recomendado: 'intermedio',
    curva_aprendizaje: 3,
    compatibilidad_proyecto: {
      app_compleja: 5,
      sitio_informativo: 3,
      ecommerce: 4,
      spa: 5,
      dashboard: 5,
      alto_trafico: 4,
    },
    rendimiento: 4,
    soporte_ssr: 1,
    compatibilidad_movil: 4,
    adaptacion_equipo: {
      individual: 4,
      equipo_pequeño: 5,
      equipo_grande: 4,
    },
    flexibilidad_estructura: 5,
    caracteristicas: {
      facilidad_uso: 3,
      rendimiento: 4,
      escalabilidad: 5,
      comunidad: 5,
      popularidad_laboral: 5,
      ecosistema: 5,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 3,
      carga_rapida: 4,
      accesibilidad: 4,
      seo: 3,
    },
    url_documentacion: 'https://reactjs.org/docs/getting-started.html',
  },
  {
    id: 2,
    nombre: 'Angular',
    nivel_experiencia_recomendado: 'avanzado',
    curva_aprendizaje: 5,
    compatibilidad_proyecto: {
      app_compleja: 5,
      sitio_informativo: 2,
      ecommerce: 4,
      spa: 5,
      dashboard: 5,
      alto_trafico: 4,
    },
    rendimiento: 3,
    soporte_ssr: 2,
    compatibilidad_movil: 3,
    adaptacion_equipo: {
      individual: 2,
      equipo_pequeño: 3,
      equipo_grande: 5,
    },
    flexibilidad_estructura: 2,
    caracteristicas: {
      facilidad_uso: 2,
      rendimiento: 3,
      escalabilidad: 5,
      comunidad: 4,
      popularidad_laboral: 4,
      ecosistema: 4,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 1,
      carga_rapida: 2,
      accesibilidad: 4,
      seo: 4,
    },
    url_documentacion: 'https://angular.io/docs',
  },
  {
    id: 3,
    nombre: 'Vue.js',
    nivel_experiencia_recomendado: 'principiante',
    curva_aprendizaje: 2,
    compatibilidad_proyecto: {
      app_compleja: 4,
      sitio_informativo: 4,
      ecommerce: 4,
      spa: 5,
      dashboard: 4,
      alto_trafico: 3,
    },
    rendimiento: 4,
    soporte_ssr: 1,
    compatibilidad_movil: 3,
    adaptacion_equipo: {
      individual: 5,
      equipo_pequeño: 5,
      equipo_grande: 3,
    },
    flexibilidad_estructura: 4,
    caracteristicas: {
      facilidad_uso: 5,
      rendimiento: 4,
      escalabilidad: 4,
      comunidad: 4,
      popularidad_laboral: 3,
      ecosistema: 4,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 5,
      carga_rapida: 4,
      accesibilidad: 3,
      seo: 3,
    },
    url_documentacion: 'https://vuejs.org/guide/introduction.html',
  },
  {
    id: 4,
    nombre: 'Svelte',
    nivel_experiencia_recomendado: 'principiante',
    curva_aprendizaje: 2,
    compatibilidad_proyecto: {
      app_compleja: 3,
      sitio_informativo: 5,
      ecommerce: 3,
      spa: 4,
      dashboard: 3,
      alto_trafico: 3,
    },
    rendimiento: 5,
    soporte_ssr: 1,
    compatibilidad_movil: 2,
    adaptacion_equipo: {
      individual: 5,
      equipo_pequeño: 4,
      equipo_grande: 2,
    },
    flexibilidad_estructura: 3,
    caracteristicas: {
      facilidad_uso: 5,
      rendimiento: 5,
      escalabilidad: 3,
      comunidad: 3,
      popularidad_laboral: 2,
      ecosistema: 2,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 5,
      carga_rapida: 5,
      accesibilidad: 3,
      seo: 3,
    },
    url_documentacion: 'https://svelte.dev/docs',
  },
  {
    id: 5,
    nombre: 'Next.js',
    nivel_experiencia_recomendado: 'intermedio',
    curva_aprendizaje: 3,
    compatibilidad_proyecto: {
      app_compleja: 4,
      sitio_informativo: 5,
      ecommerce: 5,
      spa: 4,
      dashboard: 4,
      alto_trafico: 5,
    },
    rendimiento: 4,
    soporte_ssr: 2,
    compatibilidad_movil: 3,
    adaptacion_equipo: {
      individual: 4,
      equipo_pequeño: 5,
      equipo_grande: 4,
    },
    flexibilidad_estructura: 4,
    caracteristicas: {
      facilidad_uso: 4,
      rendimiento: 5,
      escalabilidad: 5,
      comunidad: 4,
      popularidad_laboral: 4,
      ecosistema: 4,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 3,
      carga_rapida: 5,
      accesibilidad: 4,
      seo: 5,
    },
    url_documentacion: 'https://nextjs.org/docs',
  },
  {
    id: 6,
    nombre: 'Nuxt.js',
    nivel_experiencia_recomendado: 'intermedio',
    curva_aprendizaje: 3,
    compatibilidad_proyecto: {
      app_compleja: 4,
      sitio_informativo: 5,
      ecommerce: 5,
      spa: 4,
      dashboard: 4,
      alto_trafico: 4,
    },
    rendimiento: 4,
    soporte_ssr: 2,
    compatibilidad_movil: 3,
    adaptacion_equipo: {
      individual: 4,
      equipo_pequeño: 5,
      equipo_grande: 3,
    },
    flexibilidad_estructura: 3,
    caracteristicas: {
      facilidad_uso: 4,
      rendimiento: 4,
      escalabilidad: 4,
      comunidad: 3,
      popularidad_laboral: 3,
      ecosistema: 3,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 3,
      carga_rapida: 4,
      accesibilidad: 3,
      seo: 5,
    },
    url_documentacion: 'https://nuxtjs.org/docs',
  },
  {
    id: 7,
    nombre: 'Ember.js',
    nivel_experiencia_recomendado: 'avanzado',
    curva_aprendizaje: 4,
    compatibilidad_proyecto: {
      app_compleja: 5,
      sitio_informativo: 2,
      ecommerce: 3,
      spa: 4,
      dashboard: 5,
      alto_trafico: 3,
    },
    rendimiento: 3,
    soporte_ssr: 1,
    compatibilidad_movil: 2,
    adaptacion_equipo: {
      individual: 2,
      equipo_pequeño: 3,
      equipo_grande: 5,
    },
    flexibilidad_estructura: 1,
    caracteristicas: {
      facilidad_uso: 2,
      rendimiento: 3,
      escalabilidad: 5,
      comunidad: 3,
      popularidad_laboral: 2,
      ecosistema: 3,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 4,
      bundle_pequeño: 1,
      carga_rapida: 2,
      accesibilidad: 3,
      seo: 2,
    },
    url_documentacion: 'https://guides.emberjs.com',
  },
  {
    id: 8,
    nombre: 'Preact',
    nivel_experiencia_recomendado: 'intermedio',
    curva_aprendizaje: 3,
    compatibilidad_proyecto: {
      app_compleja: 3,
      sitio_informativo: 4,
      ecommerce: 3,
      spa: 4,
      dashboard: 3,
      alto_trafico: 4,
    },
    rendimiento: 5,
    soporte_ssr: 1,
    compatibilidad_movil: 3,
    adaptacion_equipo: {
      individual: 4,
      equipo_pequeño: 4,
      equipo_grande: 3,
    },
    flexibilidad_estructura: 5,
    caracteristicas: {
      facilidad_uso: 3,
      rendimiento: 5,
      escalabilidad: 3,
      comunidad: 3,
      popularidad_laboral: 2,
      ecosistema: 3,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 5,
      carga_rapida: 5,
      accesibilidad: 3,
      seo: 3,
    },
    url_documentacion: 'https://preactjs.com/guide/v10/getting-started',
  },
  {
    id: 9,
    nombre: 'Svelte Kit',
    nivel_experiencia_recomendado: 'principiante',
    curva_aprendizaje: 2,
    compatibilidad_proyecto: {
      app_compleja: 4,
      sitio_informativo: 5,
      ecommerce: 4,
      spa: 4,
      dashboard: 3,
      alto_trafico: 4,
    },
    rendimiento: 5,
    soporte_ssr: 2,
    compatibilidad_movil: 2,
    adaptacion_equipo: {
      individual: 5,
      equipo_pequeño: 4,
      equipo_grande: 2,
    },
    flexibilidad_estructura: 3,
    caracteristicas: {
      facilidad_uso: 5,
      rendimiento: 5,
      escalabilidad: 3,
      comunidad: 3,
      popularidad_laboral: 2,
      ecosistema: 2,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 5,
      carga_rapida: 5,
      accesibilidad: 3,
      seo: 5,
    },
    url_documentacion: 'https://kit.svelte.dev/docs',
  },
  {
    id: 10,
    nombre: 'Alpine.js',
    nivel_experiencia_recomendado: 'principiante',
    curva_aprendizaje: 1,
    compatibilidad_proyecto: {
      app_compleja: 2,
      sitio_informativo: 5,
      ecommerce: 2,
      spa: 2,
      dashboard: 3,
      alto_trafico: 3,
    },
    rendimiento: 5,
    soporte_ssr: 0,
    compatibilidad_movil: 1,
    adaptacion_equipo: {
      individual: 5,
      equipo_pequeño: 4,
      equipo_grande: 2,
    },
    flexibilidad_estructura: 4,
    caracteristicas: {
      facilidad_uso: 5,
      rendimiento: 4,
      escalabilidad: 2,
      comunidad: 2,
      popularidad_laboral: 1,
      ecosistema: 1,
    },
    compatibilidad_restricciones: {
      navegadores_antiguos: 3,
      bundle_pequeño: 5,
      carga_rapida: 5,
      accesibilidad: 3,
      seo: 4,
    },
    url_documentacion: 'https://alpinejs.dev/start-here',
  },
]

export const questions = [
  {
    id: 1,
    question: '¿Cuál es tu nivel de experiencia en desarrollo web?',
    options: [
      { id: 'p', text: 'Principiante (menos de 1 año)' },
      { id: 'i', text: 'Intermedio (1 a 3 años)' },
      { id: 'a', text: 'Avanzado (más de 3 años)' },
    ],
  },
  {
    id: 2,
    question: '¿Qué tipo de aplicación planeas desarrollar?',
    options: [
      { id: 'info', text: 'Sitio informativo (Landing page)' },
      { id: 'ecom', text: 'Tienda online (E-commerce)' },
      { id: 'spa', text: 'Aplicación de una sola página (SPA)' },
      { id: 'mpa', text: 'Aplicación de múltiples páginas (MPA)' },
      { id: 'dash', text: 'Dashboard/Panel administrativo' },
      { id: 'traf', text: 'Aplicación con alto tráfico de usuarios' },
      { id: 'otra', text: 'Otra' },
    ],
  },
  {
    id: 3,
    question:
      '¿Prefieres trabajar con un framework con curva de aprendizaje rápida o uno más complejo pero más potente?',
    options: [
      { id: 'rapido', text: 'Prefiero aprender rápido.' },
      {
        id: 'complejo',
        text: 'Prefiero invertir tiempo en aprender algo más complejo.',
      },
      { id: 'balance', text: 'Balance entre facilidad y potencia.' },
    ],
  },
  {
    id: 4,
    question:
      '¿Consideras que el rendimiento de la aplicación es muy importante para tu proyecto?',
    options: [
      { id: 'muy', text: 'Muy importante' },
      { id: 'imp', text: 'Importante' },
      { id: 'neu', text: 'Neutral' },
    ],
  },
  {
    id: 5,
    question:
      '¿Necesitas un framework que soporta renderizado del lado del servidor (SSR)?',
    options: [
      { id: 'si', text: 'Sí' },
      { id: 'util', text: 'Sería útil' },
      { id: 'no', text: 'No es necesario' },
      { id: 'ns', text: 'No estoy seguro' },
    ],
  },
  {
    id: 6,
    question: '¿Planeas desarrollar también una aplicación móvil?',
    options: [
      { id: 'si', text: 'Sí' },
      { id: 'no', text: 'No, solo desarrollo web' },
    ],
  },
  {
    id: 7,
    question: '¿Cuál es el tamaño de tu equipo de desarrollo?',
    options: [
      { id: 'solo', text: 'Solo yo (1 persona)' },
      { id: 'peq', text: 'Equipo pequeño (2 a 5 personas)' },
      { id: 'grande', text: 'Equipo grande (más de 5 personas)' },
    ],
  },
  {
    id: 8,
    question: '¿Qué tipo de ecosistema prefieres?',
    options: [
      { id: 'comp', text: 'Completo (con convenciones establecidas)' },
      { id: 'flex', text: 'Flexible (más libertad de elección)' },
      { id: 'bal', text: 'Balance entre estructura y flexibilidad' },
    ],
  },
  {
    id: 9,
    question:
      '¿Qué características son prioritarias para tu proyecto? (selecciona 1 o 2)',
    options: [
      { id: 'facil', text: 'Facilidad de uso' },
      { id: 'rend', text: 'Rendimiento' },
      { id: 'escala', text: 'Escalabilidad' },
      { id: 'pop', text: 'Popularidad en el mercado laboral' },
      { id: 'eco', text: 'Ecosistema de componentes y librerías' },
    ],
    multiSelect: true,
    maxSelections: 2,
  },
  {
    id: 10,
    question: '¿Tienes alguna restricción tecnológica específica?',
    options: [
      { id: 'nav', text: 'Compatibilidad con navegadores antiguos' },
      { id: 'bundle', text: 'Tamaño del bundle mínimo' },
      { id: 'carga', text: 'Tiempos de carga muy rápidos' },
      { id: 'acc', text: 'Accesibilidad (WCAG)' },
      { id: 'seo', text: 'SEO optimizado' },
      { id: 'none', text: 'Ninguna restricción específica' },
    ],
  },
]
